version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data	
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - pgnetwork
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    entrypoint: >
      sh -c "mkdir -p /var/lib/pgadmin/storage/admin_admin.com &&
             cp /pgadmin4/servers.json /var/lib/pgadmin/storage/admin_admin.com/servers.json &&
             chmod 600 /var/lib/pgadmin/storage/admin_admin.com/servers.json &&
             /entrypoint.sh"

networks:
  pgnetwork:

volumes:
  pgadmin-data:

